"""Generate the two-cell standalone notebook from readable repository sources."""
from pathlib import Path
import base64
import hashlib
import io
import json
import zipfile

ROOT = Path(__file__).resolve().parents[1]


def payload():
    paths = sorted((ROOT/'src/breezesprint26').glob('*.py'))
    paths += [ROOT/'src/breezesprint26/model.json', ROOT/'requirements-tpu.lock']
    bio = io.BytesIO()
    with zipfile.ZipFile(bio, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for path in paths:
            info = zipfile.ZipInfo(path.relative_to(ROOT).as_posix(), date_time=(2026,9,21,0,0,0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, path.read_bytes())
    data = bio.getvalue()
    return data, [p.relative_to(ROOT).as_posix() for p in paths]


def build():
    data, names = payload()
    digest = hashlib.sha256(data).hexdigest()
    code1 = '''#@title 1 · Prepare BreezeSprint26 v0.1.1
#@markdown **First:** Runtime → Change runtime type → TPU v5e-1 (free quota permitting).
#@markdown 台語輸入、中文文字輸出。第二格上傳，完成後自動下載時間戳 TXT；不需 API key。
# Full sources: https://github.com/thc1006/breezesprint-26 · Independent integration, not an official Google/MediaTek/NYCU release.
# This standalone notebook embeds the same readable source files as the repository. No source downloads.
import base64, hashlib, importlib, io, json, sys, zipfile
from pathlib import Path

if "sprint" in globals():
    sprint.close()
# Generated by tools/build_notebook.py; the payload contains Python SOURCE, not model weights.
# Its digest detects corruption, not the trustworthiness of the publisher.
PAYLOAD_SHA256 = "__DIGEST__"
PAYLOAD_FILES = __FILES__
PAYLOAD_B64 = "__PAYLOAD__"
raw = base64.b64decode(PAYLOAD_B64, validate=True)
if hashlib.sha256(raw).hexdigest() != PAYLOAD_SHA256:
    raise RuntimeError("Notebook source payload checksum mismatch. Download a clean copy.")
bundle = Path("/content/breezesprint26/app")
bundle.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(raw)) as z:
    if sorted(z.namelist()) != sorted(PAYLOAD_FILES):
        raise RuntimeError("Unexpected notebook payload files.")
    for info in z.infolist():
        dest = (bundle/info.filename).resolve()
        if not dest.is_relative_to(bundle.resolve()) or info.file_size > 2_000_000:
            raise RuntimeError("Unsafe notebook payload path or size.")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(z.read(info.filename))
# Colab's kernel imports only the stdlib controller. JAX stays in the isolated worker.
for key in list(sys.modules):
    if key == "breezesprint26" or key.startswith("breezesprint26."):
        del sys.modules[key]
sys.path.insert(0, str(bundle/"src"))
from breezesprint26.colab import setup
sprint = setup(bundle)
del raw
'''.replace('__DIGEST__',digest).replace('__FILES__',repr(names)).replace('__PAYLOAD__',base64.b64encode(data).decode())
    code2 = '''#@title 2 · 上傳台語輸入、中文文字輸出錄音 → 自動轉錄 → 下載 TXT
#@markdown 只提供上傳介面。台語輸入、中文文字輸出；沒有模型選單。
#@markdown Experimental Breeze TPU port: hardware execution and accuracy still require validation.
#@markdown Each finished recording downloads as its own .txt with SRT-style time ranges. No ZIP.
#@markdown For another recording, rerun this cell; the model remains loaded.
if "sprint" not in globals():
    raise RuntimeError("Run setup cell 1 first, then rerun this upload cell.")
from breezesprint26.colab import upload_and_transcribe
text_files = upload_and_transcribe(sprint)
'''
    nb = dict(nbformat=4, nbformat_minor=5,
              metadata=dict(accelerator='TPU', colab=dict(name='BreezeSprint26.ipynb', provenance=[], tpuType='V5E1'),
                            kernelspec=dict(display_name='Python 3', language='python', name='python3'),
                            language_info=dict(name='python')),
              cells=[dict(cell_type='code', id=f'breezesprint26-{i}', execution_count=None,
                          metadata=dict(id=f'breezesprint26-{i}', cellView='form'), outputs=[],
                          source=code.splitlines(keepends=True)) for i,code in enumerate([code1,code2],1)])
    (ROOT/'BreezeSprint26.ipynb').write_text(json.dumps(nb,ensure_ascii=False,indent=1)+'\n')
    return digest


if __name__ == '__main__':
    print(build())
